version: '3'

services:
  proxy:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - auth_service
      - notes_service

  auth_service:
    image: auth_service
    build:
      context: ./auth_service
      dockerfile: Dockerfile
    expose:
      - "5000"

  notes_service:
    image: notes_service
    build:
      context: ./notes_service
      dockerfile: Dockerfile
    expose:
      - "5001"